version: 2.1
jobs:
  build_bin:
    docker:
      - image: cimg/rust:1.68.0
    resource_class: medium
    steps:
      - checkout # TODO shallow
      - run:
          name: install dependencies (clang)
          command: scripts/install_clang.sh && rustup target add x86_64-unknown-linux-musl
      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
      - run:
          name: build ferris-ci
          command: llvm_postfix=-14 scripts/build_ferris_ci.sh
      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - ~/.cargo/git
      - persist_to_workspace:
          root: .
          paths:
            - ferris-ci
  build_image:
    parameters:
      image:
        type: string
      base_image:
        type: string
        default: "full"
    docker:
      - image: cimg/python:3.11.3
    resource_class: small
    steps:
      - checkout # TODO shallow
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: build
          command: |
            docker build --tag ghcr.io/pascalkuthe/<< parameters.image >> -f containers/<< parameters.image >> .

      - run:
          name: squash
          command: |
            pip install docker==6.1.1
            pip install docker-squash==1.1.0
            if [ << parameters.base_image >> == 'full' ]
            then
              docker-squash ghcr.io/pascalkuthe/<< parameters.image >>
            fi
      - when:
          condition:
              equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: deploy
                command: |
                  echo $GITHUB_TOKEN | docker login ghcr.io -u pascalkuthe --password-stdin
                  docker push ghcr.io/pascalkuthe/<< parameters.image >>

workflows:
  ci:
    jobs:
      - build_bin:
          name: build ferris_ci binary
      - hold:
          type: approval # presents manual approval button in the UI
      - build_image:
          requires:
            - build ferris_ci binary
            - hold
          context: github
          base_image: ubuntu:22.04
          matrix:
            parameters:
              image: 
              - ferris_ci_clippy
              - ferris_ci_fmt
              - ferris_ci_dep
              - ferris_ci_vendor
              - ferris_ci_test_runner_x86_64-pc-windows-msvc
              - ferris_ci_test_runner_x86_64-unknown-linux-gnu 

      - build_image:
          requires:
            - build ferris_ci binary
            - hold
          context: github
          matrix:
            parameters:
              image: 
              - ferris_ci_build_x86_64-pc-windows-msvc
              - ferris_ci_build_x86_64-unknown-linux-gnu 
